//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.boynton.store;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

//
// Items - A Listing is a set of items, with an optional 'next' value to pass
// to skip in a subsequent call.
//
public class Items {
    public List<Item> items;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String next;

    public String toString() {
        return JSON.pretty(this);
    }

    public Items items(List<Item> items) {
        this.items = items;
        return this;
    }

    public Items next(String next) {
        this.next = next;
        return this;
    }

}
