//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.boynton.store;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

//
// Item - Items are what get stored
//
public class Item {
    public String id;

    public String toString() {
        return JSON.pretty(this);
    }

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String created;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String modified;

    public String name;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String description;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public List<String> related;

    public Item id(String id) {
        this.id = id;
        return this;
    }
    public Item created(String created) {
        this.created = created;
        return this;
    }
    public Item modified(String modified) {
        this.modified = modified;
        return this;
    }
    public Item name(String name) {
        this.name = name;
        return this;
    }
    public Item description(String description) {
        this.description = description;
        return this;
    }
    public Item related(List<String> related) {
        this.related = related;
        return this;
    }

}
